// ES → EN: términos base que matchean con Lucide
export const ES_SYNONYMS: Record<string, string[]> = {
  flecha: ["arrow", "chevron"],
  derecha: ["right", "east"],
  izquierda: ["left", "west"],
  arriba: ["up", "north"],
  abajo: ["down", "south"],
  calendario: ["calendar", "date"],
  agenda: ["calendar"],
  reloj: ["clock", "time", "watch", "timer", "alarm"],
  usuario: ["user", "person", "profile", "account"],
  personas: ["users", "group", "team"],
  buscar: ["search"],
  inicio: ["home", "house"],
  cerrar: ["x", "close"],
  aceptar: ["check", "ok", "success", "done"],
  advertencia: ["alert-triangle", "warning"],
  info: ["info", "information", "circle-help"],
  error: ["bug", "x", "ban", "alert-octagon"],
  agregar: ["plus", "add", "new", "create"],
  quitar: ["minus", "remove"],
  borrar: ["trash", "delete", "bin"],
  editar: ["edit", "pencil"],
  guardar: ["save", "floppy"],
  subir: ["upload"],
  descargar: ["download"],
  reproducir: ["play"],
  pausar: ["pause"],
  detener: ["stop", "square"],
  correo: ["mail", "email", "envelope"],
  telefono: ["phone", "call"],
  candado: ["lock", "unlock", "shield", "key"],
  ver: ["eye", "view", "reveal"],
  ocultar: ["eye-off", "hide"],
  favorito: ["star", "heart", "bookmark"],
  "me-gusta": ["thumbs-up", "like"],
  "no-me-gusta": ["thumbs-down"],
  mapa: ["map"],
  ubicacion: ["map-pin", "pin", "navigation", "locate"],
  marcador: ["bookmark", "map-pin"],
  archivo: ["file", "document", "note"],
  carpeta: ["folder"],
  grafica: ["chart", "bar-chart", "line-chart", "pie-chart"],
  estadistica: ["chart", "analytics"],
  campana: ["bell", "notification"],
  nube: ["cloud"],
  enlace: ["link", "chain"],
  compartir: ["share"],
  camara: ["camera"],
  imagen: ["image", "picture", "photo"]
};
